### ISSUE TITLE
nushell / jq notes

### ISSUE THREAD

**Issue by fdncred** [arnau/seachess#35]
Wow! What a great article. I love the from-jq-to-nushell. Great job! I've wondered about that and thought of doing the same thing. I think this would make for a great blog post in our nushell cookbook.

One thing that I noticed that could be done differently was the grouping and aggregation section. What you have is technically correct. However, we've recently improved group-by.

Example - Your code
```nushell
'[{"category": "A", "value": 10}, {"category": "B", "value": 20}, {"category": "A", "value": 5}]' 
| from json
| group-by category
| transpose category value
| update value { |row| $row.value.value | math sum }
```
Example - Newly update
```nushell
'[{"category": "A", "value": 10}, {"category": "B", "value": 20}, {"category": "A", "value": 5}]' 
| from json
| group-by category --to-table
| update value { |row| $row.items.value | math sum }
```

This new `--to-table` functionality of `group-by` is loads faster than using transpose.

I'd also like to think about some of your toolkit custom commands. I'm wondering if we should include rust commands or enhancements to help with that functionality? Please let me know what you think.

If you're interested in contributing to our [cookbook](https://www.nushell.sh/cookbook/) just ping me.

Once again, great job porting jq to nushell!!! ❤️

**Comment by arnau** [comment]
Thanks for your kind words @fdncred 

> I'd also like to think about some of your toolkit custom commands. I'm wondering if we should include rust commands or enhancements to help with that functionality? Please let me know what you think.

I haven't looked into Rust commands yet. I presume porting some of my nu commands to Rust would speed them up however it would increase the difficulty of following along the guideline? I'm open to suggestions :)

> If you're interested in contributing to our [cookbook](https://www.nushell.sh/cookbook/) just ping me.

What do you have in mind? I'd be happy to help with the cookbook.

**Comment by arnau** [comment]
I adopted the `--to-table` flag. Much more intuitive 🙏

**Comment by fdncred** [comment]
> What do you have in mind? I'd be happy to help with the cookbook.

Duplicating your blog post in our cookbook and putting a link at the bottom thanking you for letting us post your blog "here" with a link to your blog maybe?

> I adopted the --to-table flag. Much more intuitive 🙏

Glad you like it. It is more intuitive but more than that, it's incredibly faster. You'd notice that if you were transposing a larger list.

**Comment by arnau** [comment]
> Duplicating your blog post in our cookbook and putting a link at the bottom thanking you for letting us post your blog "here" with a link to your blog maybe?

Sounds good 👍 I can to that in the next few days actually. I might reshuffle the order to make it more incremental. My blog post followed the original jq guide which I might not always agree with :)

**Comment by fdncred** [comment]
Sounds good. Appreciate you helping nushell with this. I think people will find this interesting.
